name: CI
on:
  push:
  pull_request:
  # Run monthly as a canary for issues such as package installation failure.
  # Note: scheduled workflows are disabled automatically after 60 days of
  # repository inactivity.
  # https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
  schedule:
    - cron: '46 3 20 * *'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        playbook:
          - user.yml
          - root.yml
        platform:
          - centos
          - debian
          - ubuntu

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tests

    steps:
      - uses: actions/checkout@v3

      - name: Launch containers
        run: ls -1 ./dockerfiles/ | fgrep ${{ matrix.platform }} | xargs docker-compose up -d

      - name: Run The Tests
        run: ansible-playbook ${{ matrix.playbook }} -l ${{ matrix.platform }}

      - name: Shut down containers
        run: docker-compose down
